 CREATE OR replace VIEW srh_edifecs_dev.tx_tchp_encounters_100 as 
 SELECT    '100'                                                                                      AS c_100_record,
           'SR'::character VARYING::text|| lpad(ird.ride_id::character VARYING::text, 16, '0'::character VARYING::text) AS c_100_key,
           ''                                                                                         AS c_claimstatus,
           'ProfClaim'                                                                                AS c_claimtype,
           'SAFERIDE01'                                                                               AS c_senderid,
           'EDIFECSTCHTXCD'                                                                           AS c_receiver_id_,
           ''                                                                                         AS c_originatorid,
           ''                                                                                         AS c_contract_id,
           '617591011TEDP'                                                                                    AS c_destinationid,
           'False'                                                                                    AS c_historicalindicator,
           ''                                                                                         AS c_historicaldispositionstatus,
           ''                                                                                         AS c_historicalencountericn,
           ''                                                                                         AS c_historicalencounterid,
           'False'                                                                                    AS c_paper,
           'False'                                                                                    AS c_dme,
           'False'                                                                                    AS c_administrative_denial,
           ''                                                                                         AS c_chart_review_data,
           ''                                                                                         AS c_source_,
           ''                                                                                         AS c_filler,
           ''                                                                                         AS c_tracenumber,
           '41'                                                                                       AS c_1000a_nm101_submitterentityrole,
           '2'                                                                                        AS c_1000a_nm102_submitterpersonindicator,
           'SafeRide Inc.'                                                                            AS c_1000a_nm103_submitterlastname,
           '46'                                                                                       AS c_1000a_nm108_submitteridentifierqualifier,
           '645999162'                                                                                AS c_1000a_nm109_submitteridentifier,
           'IC'                                                                                       AS c_1000a_per01_01_submittercontactidentifier,
           'SAFERIDE SUPPORT'                                                                         AS c_1000a_per02_01_submittercontactname,
           'EM'                                                                                       AS c_1000a_per03_01_submittercontactqualifier1,
           'team@saferideheatlh.com'                                                                  AS c_1000a_per04_01_submittercontact1,
           'TE'                                                                                       AS c_1000a_per05_01_submittercontacqualifier2,
           '8559557433'                                                                               AS c_1000a_per06_01_submittercontact2,
           '40'                                                                                       AS c_1000b_nm101_receiverentityrole_,
           '2'                                                                                        AS c_1000b_nm102_personindicator,
           'MEDICAID OF TX'                                                                           AS c_1000b_nm103_receivername,
           '46'                                                                                       AS c_1000b_nm108_receiveridentifierqualifier,
           '617591011MTPT'                                                                            AS c_1000b_nm109_receiveridentifier,
           'BI'                                                                                       AS c_2000a_prv01_billingprovidercode,
           'PXC'                                                                                      AS c_2000a_prv02_billingprovidercodequalifier,
           '347E00000X'                                                                               AS c_2000a_prv03_billingprovidertaxonomy, -- Billing Provider Info
           '85'                                                                                       AS c_2010aa_nm101_billingproviderrole,
           '2'                                                                                        AS c_2010aa_nm102_billingpersonindicator,
           'SAFERIDE HEALTH'                                                                          AS c_2010aa_nm103_billingorg_lastname,
           ''                                                                                         AS c_2010aa_nm104_billingfirstname,
           ''                                                                                         AS c_2010aa_nm105_billingmiddlename,
           ''                                                                                         AS c_2010aa_nm107_billingsuffix,
           'XX'                                                                                       AS c_2010aa_nm108_billingprovideridentifierqualifier,
           '1235787102'                                                                               AS c_2010aa_nm109_billingprovideridentifier,
           '18302 Talavera Ridge'                                                                     AS c_2010aa_n301_billingaddressline1,
           'Suite 300'                                                                                AS c_2010aa_n302_billingaddressline2,
           'SAN ANTONIO'                                                                              AS c_2010aa_n401_billingcity,
           'TX'                                                                                       AS c_2010aa_n402_billingstate,
           '782572605'                                                                                AS c_2010aa_n403_billingpostalcode,
           ''                                                                                         AS c_2010aa_n404_billingcountry,
           'EI'                                                                                       AS c_2010aa_ref01_billingprovideridentifierqualifier_1,
           '813037449'                                                                                AS c_2010aa_ref02_billingprovideridentifier_1,
           ''                                                                                         AS c_2010aa_ref01_billingprovideridentifierqualifier_2,
           ''                                                                                         AS c_2010aa_ref02_billingprovideridentifier_2,
           ''                                                                                         AS c_2010aa_billingproviderspeciality,
           ''                                                                                         AS c_2010aa_billingprovidertype_,
           ''                                                                                         AS c_2010aa_per01_billingprovidercontactfunction_1,
           ''                                                                                         AS c_2010aa_per02_billingprovidercontactname_1,
           ''                                                                                         AS c_2010aa_per03_billingprovidercommunicationnumberqualifier_1,
           ''                                                                                         AS c_2010aa_per04_billingprovidercommunicationnumber_1,
           ''                                                                                         AS c_2010aa_per05_billingprovidercommunicationumberqualifier_1,
           ''                                                                                         AS c_2010aa_per06_billingprovidercommunicationnumber_1,
           ''                                                                                         AS c_2010aa_per07_billingprovidercommunicationumberqualifier_1,
           ''                                                                                         AS c_2010aa_per08_billingprovidercommunicationnumber_1,
           ''                                                                                         AS c_2010aa_per01_billingprovidercontactfunction_2,
           ''                                                                                         AS c_2010aa_per02_billingprovidercontactname_2,
           ''                                                                                         AS c_2010aa_per03_communicationumberqualifier_2,
           ''                                                                                         AS c_2010aa_per04_billingprovidercommunicationnumber_2,
           ''                                                                                         AS c_2010aa_per05_billingprovidercommunicationumberqualifier_2,
           ''                                                                                         AS c_2010aa_per06_billingprovidercommunicationnumber_2,
           ''                                                                                         AS c_2010aa_per07_billingprovidercommunicationumberqualifier_2,
           ''                                                                                         AS c_2010aa_per08_billingprovidercommunicationnumber_2,
           ''                                                                                         AS c_2010ab_nm101_paytoproviderrole,
           ''                                                                                         AS c_2010ab_nm102_paytopersonindicator,
           ''                                                                                         AS c_2010ab_n301_paytoaddressline1,
           ''                                                                                         AS c_2010ab_n302_paytoaddressline2,
           ''                                                                                         AS c_2010ab_n401_paytocity,
           ''                                                                                         AS c_2010ab_n402_paytostate,
           ''                                                                                         AS c_2010ab_n403_paytopostalcode,
           ''                                                                                         AS c_2010ab_n404_paytocountry,
           ''                                                                                         AS c_2010ac_nm101_paytoplanorganizationrole,
           ''                                                                                         AS c_2010ac_nm102_paytoplanpersonindicator,
           ''                                                                                         AS c_2010ac_nm103_paytoplanname,
           ''                                                                                         AS c_2010ac_nm108_paytoplanorganizationidqualifier,
           ''                                                                                         AS c_2010ac_nm109_paytoplanorganizationidentifier,
           ''                                                                                         AS c_2010ac_n301_paytoplanaddressline1,
           ''                                                                                         AS c_2010ac_n302_paytoplanaddressline2,
           ''                                                                                         AS c_2010ac_n401_paytoplancity,
           ''                                                                                         AS c_2010ac_n402_paytoplanstate,
           ''                                                                                         AS c_2010ac_n403_paytoplanpostalcode,
           ''                                                                                         AS c_2010ac_n404_paytoplancountry,
           ''                                                                                         AS c_2010ac_ref01_organizationidqualifier_1,
           ''                                                                                         AS c_2010ac_ref02_organizationidentifier_1,
           ''                                                                                         AS c_2010ac_ref01_organizationidqualifier_2,
           ''                                                                                         AS c_2010ac_ref02_organizationidentifier_2,
           ''                                                                                         AS c_claim_encounter_cleanup,
           ''                                                                                         AS c_atypical_provider_flag,
           ''                                                                                         AS c_supplemental_interim_flag,
           ''                                                                                         AS c_interim_late_charge_flag,
           ''                                                                                         AS c_issueridentifier,
           ''                                                                                         AS c_100_filler_05,
           ''                                                                                         AS c_100r_monetaryamountchangeflag,
           ''                                                                                         AS c_1000a_nm104_submitterfirstname,
           ''                                                                                         AS c_billingcountycode,
           ''                                                                                         AS c_100_filler_06,
           ''                                                                                         AS c_claiminputmethod,
           ''                                                                                         AS c_rehab_flag,
           ''                                                                                         AS c_ps_custom_field_1,
           ''                                                                                         AS c_void_reason,
           ''                                                                                         AS c_ps_custom_field_2,
           to_char(getdate(), 'YYYYMMDD'::character VARYING::text)                                    AS c_claim_processing_date,
           ''                                                                                         AS c_100_filler_13,
           ''                                                                                         AS c_100_filler_14,
           ''                                                                                         AS c_100_filler_15,
           ''                                                                                         AS c_historicalpassthroughindicator,
           ''                                                                                         AS c_historicaloriginalclaimid,
           ''                                                                                         AS c_interchange_authorization_info_qualifier,
           ''                                                                                         AS c_interchange_authorization_info,
           ''                                                                                         AS c_2010aa_billingproviderspecialitydesc,
           ''                                                                                         AS c_100_fqhc_indicator,
           ''                                                                                         AS c_100_incomplete_data_reason,
           ''                                                                                         AS c_historicalbatchreceiveddate,
           ''                                                                                         AS c_value_based_payments,
           ''                                                                                         AS c_100r_iscrossoverflag
FROM       
srh_edifecs_dev.careprovider_invoice_ride_details ird

WHERE      
1=1
and ird.zero_cost_ride = 0 and ird.transport in ('AMB','WCV')
AND ird.hospital_group_id = 238

WITH no SCHEMA binding;